### ISSUE TITLE
License circumstances should be hinted

### ISSUE THREAD

**Issue by reinerBa** [bassdman/vue-feature-toggle#2]
Hi,
thank you for coding this library, i found it on npm and checked out the github repo. Than i saw that it is released under the GPLv3 which could cause trouble for your users like described here:

`https://stackoverflow.com/a/1239727/6355502`

The most easy solution would be to change the license to a permissive one. But to do or not, this is only your right to decide as author. 
But as the installation process of the library is fortunately documented very well, the license context is not.  IMAO the restrictions like "All code linked with GPL 3.0 source code must be disclosed under a GPL 3.0 compatible license." should be listed close to the npm install command.

kind regards

**Comment by bassdman** [comment]
Hello Reiner,

thank you for your advice. I tried to find the best licence that fits the following criteria:
- everyone can use it (commercial, non commercial)
- everyone can modify it (commercial, non commercial)
- if modified it can be used in another licence.

I thought this licence was good for these criteria - but it looks like it isn't. 
The MIT-License is best for these conditions, am I right? (At least most vue projects are under MIT-license)

Best regards

Manu

**Comment by reinerBa** [comment]
This is right, MIT is a very permissive Licences and might be the best for your project. 
There are other similiar permissive licences as well like Apache v2 and BSD
https://tldrlegal.com/license/mit-license 

glad to help

**Comment by bassdman** [comment]
done.
