### ISSUE TITLE
Vue3 compatibility

### ISSUE THREAD

**Issue by wmelton** [bassdman/vue-feature-toggle#8]
The repo indicates it is compatible with Vue 3, but when doing `npm i vue-feature-toggle` a build error throws:

```
npm ERR! While resolving: audiences.frontend@1.1.0
npm ERR! Found: vue@3.2.22
npm ERR! node_modules/vue
npm ERR!   vue@"^3.2.11" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.x" from vue-feature-toggle@2.0.4
npm ERR! node_modules/vue-feature-toggle
npm ERR!   vue-feature-toggle@"*" from the root project
```

How do we build this with Vue 3 without including Vue 2 code base and resolving errors?

**Comment by andgudovich** [comment]
Peer dependencies must be updated to include Vue 3 too:
E.g. `"vue": "^2.x || ^3.x"`

**Comment by bassdman** [comment]
Hi wmelton,

thank you for finding it. I have updated the peer dependencies - now it should work with vue3. 
I had directly tried it by referencing the local folder - so this error didn't show up...

If it still does not work for you, just tell me, how you your vue-project is created (via cli,...) so I have a better chance to reproduce it.

Best regards

Manu
